# -*- coding: utf-8 -*-
"""useOfPycaret.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPX4tj6wRk37tc-Z3Oa9ykeINuVLCMn9
"""

! pip install pycaret

import pycaret
import pandas as pd
from pycaret.classification import *

pycaret.__version__

# Loading data
data = pd.read_csv('/content/gpsdata.csv')
print(data)

# Option 1: Remove the row with the missing value
data.dropna(subset=['Output'], inplace=True)

# initialization of set up

exp_clf = setup(data, target = 'Output')

print(exp_clf)

compare_models()

rf = create_model('rf')

tuned_rf = tune_model(rf)